<%@ Page Title="" Language="C#" MasterPageFile="~/Default2.master" AutoEventWireup="true" CodeFile="aproduct.aspx.cs" Inherits="aproduct" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" Runat="Server">
</asp:Content>
<asp:Content ID="Content3" ContentPlaceHolderID="ContentPlaceHolder2" Runat="Server">
    <asp:Panel ID="Panel1" runat="server" BackImageUrl="~/Images/BK.jpg" 
        Height="130px" style="margin-top: 0px">
        &nbsp;&nbsp;<br />
        <asp:Button ID="Button5" runat="server" Height="37px" onclick="Button5_Click" 
            Text="All" Width="194px" />
        <asp:Button ID="Button7" runat="server" Height="37px" onclick="Button5_Click" 
            Text="Add new " Width="194px" PostBackUrl="~/newprod.aspx" />
        <asp:Button ID="genderp0" runat="server" Height="37px" onclick="genderp_Click" 
            Text="Gender wise" Width="194px" PostBackUrl="~/agenderwise.aspx" />
        <asp:Button ID="catp" runat="server" Height="37px" onclick="catp_Click" 
            Text="Categories" Width="194px" PostBackUrl="~/acategorywise.aspx" />
        <br />
        <br />
    </asp:Panel>
<asp:Panel ID="Panel2" runat="server" Height="2344px" 
        BackImageUrl="~/Images/BK.jpg">
        <asp:SqlDataSource ID="SqlDataSource1" runat="server" 
            ConnectionString="<%$ ConnectionStrings:RConnectionString %>" 
            DeleteCommand="DELETE FROM [Data] WHERE [UNo] = @UNo" 
            InsertCommand="INSERT INTO [Data] ([UNo], [Itemname], [image], [description], [Price], [quantity], [category], [gender]) VALUES (@UNo, @Itemname, @image, @description, @Price, @quantity, @category, @gender)" 
            SelectCommand="SELECT [UNo], [Itemname], [image], [description], [Price], [quantity], [category], [gender] FROM [Data] ORDER BY [UNo]" 
            UpdateCommand="UPDATE [Data] SET [Itemname] = @Itemname, [image] = @image, [description] = @description, [Price] = @Price, [quantity] = @quantity, [category] = @category, [gender] = @gender WHERE [UNo] = @UNo">
            <DeleteParameters>
                <asp:Parameter Name="UNo" Type="String" />
            </DeleteParameters>
            <InsertParameters>
                <asp:Parameter Name="UNo" Type="String" />
                <asp:Parameter Name="Itemname" Type="String" />
                <asp:Parameter Name="image" Type="String" />
                <asp:Parameter Name="description" Type="String" />
                <asp:Parameter Name="Price" Type="String" />
                <asp:Parameter Name="quantity" Type="String" />
                <asp:Parameter Name="category" Type="String" />
                <asp:Parameter Name="gender" Type="String" />
            </InsertParameters>
            <UpdateParameters>
                <asp:Parameter Name="Itemname" Type="String" />
                <asp:Parameter Name="image" Type="String" />
                <asp:Parameter Name="description" Type="String" />
                <asp:Parameter Name="Price" Type="String" />
                <asp:Parameter Name="quantity" Type="String" />
                <asp:Parameter Name="category" Type="String" />
                <asp:Parameter Name="gender" Type="String" />
                <asp:Parameter Name="UNo" Type="String" />
            </UpdateParameters>
        </asp:SqlDataSource>
        <br />
        <br />
        <asp:GridView ID="GridView6" runat="server" AllowSorting="True" DataKeyNames="UNo" 
            DataSourceID="SqlDataSource1" BackColor="White" BorderColor="#CCCCCC" 
            BorderStyle="None" BorderWidth="1px" CellPadding="3" style="margin-left: 104px" 
            Width="1200px" AllowPaging="True" AutoGenerateDeleteButton="True" 
            AutoGenerateEditButton="True" AutoGenerateUpdateButton="True"
            onselectedindexchanged="GridView6_SelectedIndexChanged1" 
            AutoGenerateColumns="False">
            <Columns>
                <asp:TemplateField HeaderText="UNo" SortExpression="UNo">
                    <EditItemTemplate>
                        <asp:Label ID="Label1" runat="server" Text='<%# Eval("UNo") %>'></asp:Label>
                    </EditItemTemplate>
                    <ItemTemplate>
                        <asp:Label ID="Label1" runat="server" Text='<%# Bind("UNo") %>'></asp:Label>
                    </ItemTemplate>
                </asp:TemplateField>
                <asp:TemplateField HeaderText="Itemname" SortExpression="Itemname">
                    <EditItemTemplate>
                        <asp:TextBox ID="TextBox1" runat="server" Text='<%# Bind("Itemname") %>'></asp:TextBox>
                    </EditItemTemplate>
                    <ItemTemplate>
                        <asp:Label ID="Label2" runat="server" Text='<%# Bind("Itemname") %>'></asp:Label>
                    </ItemTemplate>
                </asp:TemplateField>
                <asp:TemplateField HeaderText="image" SortExpression="image">
                    <EditItemTemplate>
                        <asp:Image ID="Image4" runat="server" Height="93px" 
                            ImageUrl='<%# Bind("image") %>' Width="100px" />
                      <asp:FileUpload ID="FileUpload1" runat="server"  />
                    </EditItemTemplate>
                    <ItemTemplate>
                        <asp:Image ID="Image3" runat="server" Height="159px" 
                            ImageUrl='<%# Eval("image") %>' Width="146px" />
                    </ItemTemplate>
                </asp:TemplateField>
                <asp:TemplateField HeaderText="description" SortExpression="description">
                    <EditItemTemplate>
                        <asp:TextBox ID="TextBox3" runat="server" Text='<%# Bind("description") %>'></asp:TextBox>
                    </EditItemTemplate>
                    <ItemTemplate>
                        <asp:Label ID="Label4" runat="server" Text='<%# Bind("description") %>'></asp:Label>
                    </ItemTemplate>
                </asp:TemplateField>
                <asp:TemplateField HeaderText="Price" SortExpression="Price">
                    <EditItemTemplate>
                        <asp:TextBox ID="TextBox4" runat="server" Text='<%# Bind("Price") %>'></asp:TextBox>
                    </EditItemTemplate>
                    <ItemTemplate>
                        <asp:Label ID="Label5" runat="server" Text='<%# Bind("Price") %>'></asp:Label>
                    </ItemTemplate>
                </asp:TemplateField>
                <asp:TemplateField HeaderText="quantity" SortExpression="quantity">
                    <EditItemTemplate>
                        <asp:TextBox ID="TextBox5" runat="server" Text='<%# Bind("quantity") %>'></asp:TextBox>
                    </EditItemTemplate>
                    <ItemTemplate>
                        <asp:Label ID="Label6" runat="server" Text='<%# Bind("quantity") %>'></asp:Label>
                    </ItemTemplate>
                </asp:TemplateField>
                <asp:TemplateField HeaderText="category" SortExpression="category">
                    <EditItemTemplate>
                        <asp:TextBox ID="TextBox6" runat="server" Text='<%# Bind("category") %>'></asp:TextBox>
                    </EditItemTemplate>
                    <ItemTemplate>
                        <asp:Label ID="Label7" runat="server" Text='<%# Bind("category") %>'></asp:Label>
                    </ItemTemplate>
                </asp:TemplateField>
                <asp:TemplateField HeaderText="gender" SortExpression="gender">
                    <EditItemTemplate>
                        <asp:TextBox ID="TextBox7" runat="server" Text='<%# Bind("gender") %>'></asp:TextBox>
                    </EditItemTemplate>
                    <ItemTemplate>
                        <asp:Label ID="Label8" runat="server" Text='<%# Bind("gender") %>'></asp:Label>
                    </ItemTemplate>
                </asp:TemplateField>
            </Columns>
            <FooterStyle BackColor="White" ForeColor="#000066" />
            <HeaderStyle BackColor="#006699" Font-Bold="True" ForeColor="White" />
            <PagerStyle BackColor="White" ForeColor="#000066" HorizontalAlign="Left" />
            <RowStyle ForeColor="#000066" />
            <SelectedRowStyle BackColor="#669999" Font-Bold="True" ForeColor="White" />
            <SortedAscendingCellStyle BackColor="#F1F1F1" />
            <SortedAscendingHeaderStyle BackColor="#007DBB" />
            <SortedDescendingCellStyle BackColor="#CAC9C9" />
            <SortedDescendingHeaderStyle BackColor="#00547E" />
        </asp:GridView>
        </asp:Panel>
    <p>
    </p>
    <p>
    </p>
    <p>
    </p>
    <p>
    </p>
    <p>
    </p>
</asp:Content>


